### ISSUE TITLE
Решение проблемы с members.csv

### ISSUE THREAD

**Issue by FaceOyssu69** [elizhabs/TGPars#10]
Удалил файл после парсинга. После создал новый csv Лист и начал парсинг повторно, но вышла ошибка 
Traceback (most recent call last):
  File "C:\Users\SuperUser\Desktop\TGPars\invite.py", line 52, in <module>
    with open(input_file, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'members.csv'

Подскажите пожалуйста решение проблемы. Благодарю.

**Comment by gavron13** [comment]
> Удалил файл после парсинга. После создал новый csv Лист и начал парсинг повторно, но вышла ошибка Traceback (most recent call last): File "C:\Users\SuperUser\Desktop\TGPars\invite.py", line 52, in with open(input_file, encoding='UTF-8') as f: FileNotFoundError: [Errno 2] No such file or directory: 'members.csv'
> 
> Подскажите пожалуйста решение проблемы. Благодарю.

Привет! Находил способ решения?

**Comment by FaceOyssu69** [comment]
ДА. Снес винду и переустановил заново( Других решений я не придумал\не нашел...
 
 
--
vfvdfnjjhb bjhbjhbjh
Отправлено из Почты  Mail.ru
 
  
>Воскресенье, 31 июля 2022, 11:59 +05:00 от gavron13 ***@***.***>:
> 
> 
>Удалил файл после парсинга. После создал новый csv Лист и начал парсинг повторно, но вышла ошибка Traceback (most recent call last): File "C:\Users\SuperUser\Desktop\TGPars\invite.py", line 52, in with open(input_file, encoding='UTF-8') as f: FileNotFoundError: [Errno 2] No such file or directory: 'members.csv'
>Подскажите пожалуйста решение проблемы. Благодарю.
Привет! Находил способ решения?

**Comment by sunnyitalia** [comment]
Была похожая проблема, но снести достаточно было прогу и распаковать архив со скриптом заново
