### ISSUE TITLE
Always invalid id/hash

### ISSUE THREAD

**Issue by HeavyMaverick** [elizhabs/TGPars#13]
```
Traceback (most recent call last):
  File "pars.py", line 38, in <module>
    client.send_code_request(phone)
  File "C:\Users\Wlthy\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Wlthy\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Wlthy\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\auth.py", line 519, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "C:\Users\Wlthy\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Wlthy\AppData\Local\Programs\Python\Python38\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)``
```

**Comment by JenosSuiside** [comment]
Write the number without "+" on the line start.
