### ISSUE TITLE
pars.py doesn't work anymore

### ISSUE THREAD

**Issue by bs2030** [elizhabs/TGPars#6]
pars.py doesn't work anymore

Got this since february 2022

Traceback (most recent call last):
  File "C:\TG-INVITE\40\TGPars-main\pars.py", line 79, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x000001A94182DE40>, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x000001A940ABE9E0>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x000001A941838A00>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940970F10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940970FD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971090>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971150>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971210>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A9409712D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971390>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971450>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971510>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A9409715D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971690>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971750>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971810>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A9409718D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971990>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971A50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971B10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971BD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971C90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971D50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971E10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971ED0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940971F90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940972050>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A940972110>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000001A9409721D0>])

**Comment by BakulinT** [comment]
Possible solution to the problem. Changed the aggressive parameter in line 79 to False. In this case, the pars limit will be 10k people
```C#
all_participants = client.get_participants(target_group, aggressive=False)
```

**Comment by i-4m-n0-n4m3** [comment]
In pars.py file
line 79
all_participants = client.get_participants(target_group, aggressive=True)
Replace with
all_participants = client.get_participants(target_group)
 
 
 100% solution
